version: '3.8'

services:
  pandoc:
    build:
      context: .
      dockerfile: Dockerfile
    image: pandoc-latex:3.8.3
    volumes:
      - .:/data
      - ./templates:/data/templates
    working_dir: /data
    command: /bin/sh
